// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8gmOlcoZ11OkBUKpWFN13vHiuFrwLPk',
    appId: '1:382397463075:web:b437a69a41d05b3f984f96',
    messagingSenderId: '382397463075',
    projectId: 'nextalk-5724e',
    authDomain: 'nextalk-5724e.firebaseapp.com',
    storageBucket: 'nextalk-5724e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJ-jZhA22SnYdvALGZh_O-WgKT8T2R7E',
    appId: '1:382397463075:android:2f7e69ed5adee8ba984f96',
    messagingSenderId: '382397463075',
    projectId: 'nextalk-5724e',
    storageBucket: 'nextalk-5724e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ANbqo-dtm0VTzsIQ1FY7OCZ9p1wvYGQ',
    appId: '1:382397463075:ios:463015274bc48aa2984f96',
    messagingSenderId: '382397463075',
    projectId: 'nextalk-5724e',
    storageBucket: 'nextalk-5724e.firebasestorage.app',
    iosBundleId: 'com.example.pulsechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ANbqo-dtm0VTzsIQ1FY7OCZ9p1wvYGQ',
    appId: '1:382397463075:ios:463015274bc48aa2984f96',
    messagingSenderId: '382397463075',
    projectId: 'nextalk-5724e',
    storageBucket: 'nextalk-5724e.firebasestorage.app',
    iosBundleId: 'com.example.pulsechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8gmOlcoZ11OkBUKpWFN13vHiuFrwLPk',
    appId: '1:382397463075:web:fb83c17c538c4747984f96',
    messagingSenderId: '382397463075',
    projectId: 'nextalk-5724e',
    authDomain: 'nextalk-5724e.firebaseapp.com',
    storageBucket: 'nextalk-5724e.firebasestorage.app',
  );
}
